ProjectLibertyLabs/graph-sdk

- core/src/dsnp/api_types.rs
- core/src/dsnp/dsnp_types.rs
- core/src/graph/mod.rs
- core/src/graph/updates.rs
- core/src/lib.rs
The goal of this PR is  to add Update Tracking capability in graph which allows efficient page updates to be generated for the  chain related graph data.
closes #6 
added some more documentation to types
> Update tracker and update events implementation

- .github/pull_request_template.md
- .github/workflows/pr-verify.yml
- Cargo.lock
- core/Cargo.toml
- core/src/dsnp/api_types.rs
- core/src/dsnp/compression.rs
- core/src/dsnp/dsnp_types.rs
- core/src/dsnp/encryption.rs
- core/src/dsnp/pseudo_relationship_identifier.rs
- core/src/dsnp/tests/compression.rs
- core/src/dsnp/tests/encryption.rs
- core/src/dsnp/tests/mod.rs
- core/src/dsnp/tests/pseudo_relationship_identifier.rs
- core/src/frequency/tests/reader_writer.rs
- core/src/types.rs
- schemas/user_private_graph_chunk.json
The goal of this PR is to make sure that Prids are compatible with the test vector
related to  #9 
- It seems like that for **prid a->b** we were encrypting `id_a` as the message instead of `id_b` and using the other one as nonce. It does seem like in the early versions of the algorithm (at least mentioned in slack) we were doing this but we switched to the other way around. After switching to the latest version of the algorithm we are compatible with the [test vector](https://github.com/LibertyDSNP/prid-ts/blob/main/index.test.ts)
- Disabling clippy for now to speed up development process and we will enable and address comments when repo is in a more stable state
- moving other tests from their implementation files into their own file. We will need to have a decision about where is the …
> Prid refactor

- config/resources/configs/frequency-rococo.json
- config/resources/configs/frequency.json
- config/src/builder.rs
- config/src/lib.rs
- core/src/api/api.rs
- core/src/dsnp/api_types.rs
- core/src/dsnp/encryption.rs
- core/src/frequency/mod.rs
- core/src/frequency/reader_writer.rs
- core/src/graph/graph.rs
- core/src/graph/page.rs
- core/src/graph/updates.rs
- core/src/graph/user.rs
- core/src/lib.rs
- core/src/tests/helpers.rs
The goal of this PR is address schema_id oriented graph and api structures
related to #35 
- Using schema ids instead of connection types
- add support for different environments
> use schema ids in apis

- config/resources/configs/frequency-rococo.json
- config/resources/configs/frequency.json
- config/src/builder.rs
- config/src/lib.rs
- core/src/api/api.rs
- core/src/dsnp/api_types.rs
- core/src/dsnp/dsnp_configs.rs
- core/src/dsnp/encryption.rs
- core/src/dsnp/mod.rs
- core/src/dsnp/reader_writer.rs
- core/src/frequency/reader_writer.rs
- core/src/graph/graph.rs
- core/src/graph/key_manager.rs
- core/src/graph/page.rs
- core/src/graph/updates.rs
- core/src/graph/user.rs
- core/src/tests/helpers.rs
The goal of this PR is support new keys and dsnp versions in graph sdk.
Closes #34 
- Removed associated attributes on EncryptionBehavior since it was causing a lot rigidity and causing issue with conversion between associated attribute and concrete type, preventing for dynamic dispatch
- Replaced encryption and key types generics with Enums since it is allowing more flexibility and decoupling between dsnp version and key types for future
- Removed dsnp configuration from our config json since we would need to have them as static enums and it didn't make sense to have them dynamically
- moved some of hardcoded constants into config json
> refactoring to support dsnp versions

- core/src/api/api.rs
- core/src/graph/graph.rs
- core/src/graph/key_manager.rs
- core/src/tests/mocks.rs
- core/src/tests/mod.rs
The goal of this PR is to implement an api so that we can return one sided friendships to sdk consumers.
Closes #48 
- Implemented a new `MockUserKeyManager` to be able to setup tests more easily. 
- Added support to be able to use mock in for `UserKeyManager`
> implemented api to expose one sided friendships

- core/src/api/api.rs
- core/src/dsnp/api_types.rs
- core/src/dsnp/schema.rs
- core/src/graph/graph.rs
- core/src/graph/page.rs
- core/src/graph/shared_state_manager.rs
- core/src/util/builders.rs
- core/src/util/time.rs
- core/tests/integration_tests.rs
The goal of this PR is start the integration tests effort in graph-sdk.
Related to https://github.com/LibertyDSNP/graph-sdk/issues/42
- added prid len check on private friendship import
- finished tests for `apply_actions`
- finished tests for  `import_user_data`
- finished tests for  `get_connections_for_user_graph`
- finished tests for  `get_connections_without_keys`
- finished tests for `get_one_sided_private_friendship_connections`
- started testing for `export_updates`
> integration tests: part 2

- bridge/ffi/src/bindings.rs
- bridge/ffi/src/c_api.rs
- bridge/ffi/src/c_example/main.c
- bridge/ffi/src/utils.rs
- core/src/api/api.rs
- core/src/graph/shared_state_manager.rs
- core/tests/integration_tests.rs
The goal of this PR is provide an api to expose imported public keys
Closes #69
> api to expose imported public keys

- bridge/jni/src/api.rs
- bridge/jni/src/mappings.rs
- java/lib/src/main/java/io/amplica/graphsdk/Configuration.java
- java/lib/src/main/java/io/amplica/graphsdk/Graph.java
- java/lib/src/test/java/io/amplica/graphsdk/LibraryTest.java
The goal of this PR is implemented rest of JNI apis
Closes #83 
- implements mapping between Jni, Proto and Rust types
- Some minor cleanup in Java side for better usability
- Merging this would feature complete the SDK but there are some leftovers like integrating exception handling in JNI and ...
- Memory allocation and removal seems to be working as expected but will need to do more memory specific testing in future to make sure
> implemented jni apis

- bridge/ffi/src/c_api.rs
- bridge/ffi/src/c_example/main.c
- bridge/ffi/src/utils.rs
- bridge/jni/src/api.rs
- bridge/jni/src/mappings.rs
- core/src/api/api.rs
- core/tests/integration_tests.rs
- java/lib/src/main/java/io/amplica/graphsdk/Graph.java
- java/lib/src/main/java/io/amplica/graphsdk/Native.java
- java/lib/src/test/java/io/amplica/graphsdk/LibraryTest.java
The goal of this PR is to create a new api that without changing the state will deserialize dsnp keys.
Closes #98 
- FFI tests are not added due to issues related to lib-sodium dependency in C any help would be appreciated @saraswatpuneet
> new api to deserialize dsnp keys

- config/src/errors.rs
- core/src/api/api.rs
- core/src/graph/graph.rs
- core/src/graph/key_manager.rs
- core/src/graph/shared_state_manager.rs
- core/src/graph/updates.rs
- core/src/graph/user.rs
- core/tests/integration_tests.rs
The goal of this PR is to handle the edge case which re-imports of user data might happen after adding some updates. This would make sure that those updates are compatible with newly reimported user data and remove the non compatible ones.
Closes #49
- Handles some of the unwraps around locks that were lingering around. We still have some unwraps in methods that do not return Result types but to handle them we will need to change the method signature which is  bigger than the scope of this PR.
> edge-case: handles reimports after updates

- java/lib/build.gradle.kts
The goal of this PR is to make sure JNI library has protobuf dependency in a self contained way and we don't need to include that dependency in the upper library which is using the graphsdk
Closes #125
> changed protobuf to be self-contained dependency

- bridge/ffi/src/c_example/main.c
- bridge/node/js/graph.test.ts
- config/resources/configs/frequency-rococo.json
- config/resources/configs/frequency.json
- config/src/lib.rs
- core/tests/integration_tests.rs
The goal of this PR is to increase the number of user graphs that can be held in a single `GraphState` in order to support holding all of at least one user's connections in one `GraphState`.
Closes #134
> Increase graph limit to 10k

- bridge/node/js/graph.ts
- bridge/node/js/index.ts
- bridge/node/src/api.rs
The goal of this PR is to update node api to return list of dsnp id as string owing to node constraints with u64
> update api for  sending dsnpUserid as string

- .github/workflows/pr-verify.yml
- bridge/node/package.json
The goal of this PR is to not publish npm graphsdk package for PRs, to verify on PR a `--dry-run` is performed on package to be published 
Closes #147
> dry run PR publish

- java/lib/src/main/java/io/amplica/graphsdk/Configuration.java
- java/lib/src/test/java/io/amplica/graphsdk/LibraryTest.java
The goal of this PR is implement a getter for graph public keys schema id which is useful in custodial wallet and other projects.
Closes #158
> added getter for graphPublicKeySchemaId in jvm

- bridge/node/js/graph.test.ts
- bridge/node/js/models/import_bundle.ts
- core/src/api/api.rs
- core/src/api/api_types.rs
The goal of this PR is to set condition to allow importing `dsnpKeys` and `keyPairs` without schemaId
Closes #168
> ImportBundles: set condition to allow importing `dsnpKeys` and `keyPairs` without schemaId

- .github/workflows/pr-verify.yml
- .github/workflows/release.yml
- .tool-versions
- Makefile
- bridge/node/downloadBinaries.js
- bridge/node/package-lock.json
- bridge/node/package.json
- java/lib/build.gradle.kts
The goal of this PR is to facilitate releases for graph-sdk
Closes #102
Related to  #155 
Related to #154
- publishing pre-built binaries as release assets which gradle and node bridges can download using `make download-jni` and `make build-node-download` commands. The idea is that we currently only need non linux targets for developing.
- Used universal binaries for macOS native binaries supporting `aarch64-apple-darwin` and `x86_64-apple-darwin`
- Tried using that https://github.com/dherman/sniff-bytes/blob/main/.github/workflows/publish.yml for publishing multi-target packages but the inner actions used are all blocked and we would need to whitelist all of them .
> Github action for release

- .github/workflows/release.yml
To publish the correct version from tag we need to pass that version in `./gradlew publish`
> fix gradle publish version

- bridge/node/js/index.ts
The goal of this PR is address a bug that only happens on Macos with x86 architecture on node library and tries to load the windows binary since both darwin and win32 contained `win` in it.
Related to #154
> Refactor platform and arch logic in getTarget function

- Makefile
The goal of this PR is to avoid re-formatting all source files when we only want to generate a new `page_capacities.rs` file.
> fix: when generating page_capacities.rs, do not format other source file

- Cargo.lock
- core/Cargo.toml
- core/src/api/api.rs
- core/src/util/transactional_hashmap.rs
The goal of this PR is to address the bug in `transactional-hashmap` that instead of only keeping track of original state it was keeping track of all the intermediate states which was allocating excessive memory and causing Out of memory errors.
Closes #190 
- Fixed the implementation of transaction-hashmap to only keep track of the persisted state
> Fixed existing bug on transaction hashmap

- core/src/api/api.rs
- core/src/graph/updates.rs
- core/src/graph/user.rs
The goal of this PR is to remove some unnecessary borrowing + cloning when registering Graph update events. This should reduce some transient short-term memory usage.
> fix: remove unnecessary borrow/clone

- Cargo.lock
- bridge/common/Cargo.toml
- bridge/ffi/Cargo.toml
- bridge/jni/Cargo.toml
- bridge/node/Cargo.toml
- bridge/node/package-lock.json
- bridge/node/package.json
- config/Cargo.toml
- core/Cargo.toml
- core/src/api/api.rs
- core/src/graph/graph.rs
- core/src/tests/helpers.rs
The goal of this PR is fix the bug which exports only the last page instead of all of them when more than 1 page is created via adding connections.
Closes #194
> bugfix: fixed next page id calculation

- .github/workflows/release.yml
The goal of this PR is to fix the issue with macos releases
closes #202
> fix ci for macos default target

- java/example-graphsdk-client/build.gradle.kts
The goal of this PR is fix the PR due to 
Closes #209
> CI: replace deprecated jcenter
