ProjectLibertyLabs/graph-sdk

- Cargo.lock
- core/Cargo.toml
- core/src/dsnp/encryption.rs
- core/src/dsnp/mod.rs
- core/src/dsnp/reader_writer.rs
The goal of this PR is  to add encryption and decryption to private graph
closes #3
> add encryption to private graph

- .cargo/config.toml
- .github/pull_request_template.md
The goal of this PR is add PR template to repo
Related to #1
> repo minor changes

- config/resources/schemas/public_key_schema.json
- core/src/dsnp/dsnp_types.rs
- core/src/dsnp/schema.rs
- core/src/graph/key_manager.rs
- core/src/tests/helpers.rs
The goal of this PR is address misc changes that came out of sdk meeting
Closes #34 
- the schema id and encryption algorithm related changes are not applied yet
> applied misc changes

- core/src/api/api.rs
- core/src/graph/graph.rs
- core/src/graph/mod.rs
- core/src/graph/page.rs
- core/src/graph/pri_manager.rs
- core/src/tests/helpers.rs
The goal of this PR is implement PRI Manager which stores and retrieves all imported PRId to facilitate prid calculations and checks
Closes #31
> added pri manager

- config/src/lib.rs
- core/src/api/api.rs
- core/src/dsnp/api_types.rs
- core/src/dsnp/dsnp_configs.rs
- core/src/graph/graph.rs
- core/src/graph/key_manager.rs
- core/src/graph/page.rs
- core/src/graph/updates.rs
- core/src/graph/user.rs
- core/src/tests/helpers.rs
The goal of this PR is modify apis to support PRID usecase and allow batch processing
Closes #23 
- Tests are not fixed yet
- Batch apis would need transactional support
> modified apis to support prids and batch

- core/src/api/api.rs
- core/src/dsnp/api_types.rs
- core/src/dsnp/dsnp_configs.rs
- core/src/graph/graph.rs
- core/src/graph/page.rs
- core/src/graph/shared_state_manager.rs
- core/src/tests/helpers.rs
The goal of this PR is add more unit tests for page `try_into` and `calculate_update` functions for graph which uses PRID calculations to determine friendship
Closes #24
> more tests for page and graph

- config/resources/configs/frequency-rococo.json
- config/resources/configs/frequency.json
- config/src/builder.rs
- config/src/lib.rs
- core/src/api/api.rs
- core/src/dsnp/encryption.rs
- core/src/dsnp/schema.rs
- core/src/graph/graph.rs
- core/src/graph/page.rs
- core/src/graph/shared_state_manager.rs
- core/src/tests/helpers.rs
- core/src/util/time.rs
The goal of this PR is only remove friendship connections only if the friendship establishment is passes a certain time (90 days) and the expected PRID does not exist on the other side. 
Closes #47
> added support for time restricted prid connection removal

- core/src/api/api.rs
- core/src/graph/graph.rs
- core/src/graph/key_manager.rs
- core/src/graph/page.rs
- core/src/graph/shared_state_manager.rs
- core/src/graph/updates.rs
- core/src/graph/user.rs
- core/src/tests/mocks.rs
- core/src/util/mod.rs
- core/src/util/time.rs
- core/src/util/transactional_hashmap.rs
- core/src/util/transactional_vec.rs
The goal of this PR is support full in memory transactional operation support
Closes #40 
- Created two new Types `TransactionalHashMap` and `TransactionalVec` which tracks changes optimistically. And in case of rollback to previous state.
- in case of success or failure the highest component `Api` triggers a `commit` or `rollback` which gets propagated down into the lower components
> added full transactional operation support

- bridge/ffi/src/c_api.rs
- core/src/graph/key_manager.rs
- core/tests/common/mod.rs
- core/tests/integration_tests.rs
The goal of this PR is finish integration tests
Closes #42 
- Adds integration tests for rest of the apis
- Added memory release method for pubic keys
> integration tests 3

- bridge/jni/src/api.rs
- java/lib/src/main/java/io/amplica/graphsdk/Configuration.java
- java/lib/src/main/java/io/amplica/graphsdk/Graph.java
- java/lib/src/main/java/io/amplica/graphsdk/Native.java
The goal of this PR is to define all jni apis in rust and java side
Closes #82 
- Defines apis in jni side
- Define apis in Java side
- Some Java utility implementations
- since this is only the definition no tests are added. Tests will be added after complete implementation
> define jni apis

- .github/workflows/pr-verify.yml
- bridge/ffi/src/bindings.rs
- bridge/ffi/src/c_api.rs
- bridge/ffi/src/c_example/main.c
- bridge/ffi/src/utils.rs
- scripts/run_ffi_tests.sh
The goal of this PR is to add some ffi intg tests
Closes #59
> Intg tests for ffi

- .github/workflows/pr-verify.yml
- bridge/ffi/src/c_api.rs
- bridge/jni/src/api.rs
- bridge/jni/src/errors.rs
- bridge/jni/src/helper.rs
- bridge/jni/src/lib.rs
- bridge/jni/src/mappings.rs
- config/src/errors.rs
- config/src/lib.rs
- core/src/api/api.rs
- core/src/dsnp/api_types.rs
- core/src/graph/user.rs
- core/src/util/builders.rs
- core/tests/common/mod.rs
- core/tests/integration_tests.rs
- java/lib/src/main/java/io/amplica/graphsdk/Graph.java
- java/lib/src/main/java/io/amplica/graphsdk/exceptions/AcquiringLockException.java
- java/lib/src/main/java/io/amplica/graphsdk/exceptions/BaseGraphSdkException.java
- java/lib/src/main/java/io/amplica/graphsdk/exceptions/GraphSdkException.java
- java/lib/src/main/java/io/amplica/graphsdk/exceptions/InvalidHandleException.java
- java/lib/src/main/java/io/amplica/graphsdk/exceptions/InvalidOutputException.java
- java/lib/src/main/java/io/amplica/graphsdk/exceptions/InvalidProtoException.java
- java/lib/src/main/java/io/amplica/graphsdk/exceptions/InvalidRequestException.java
- java/lib/src/main/java/io/amplica/graphsdk/exceptions/JniException.java
- java/lib/src/main/java/io/amplica/graphsdk/exceptions/UnexpectedResponseException.java
- java/lib/src/main/java/io/amplica/graphsdk/exceptions/UnknownException.java
- java/lib/src/test/java/io/amplica/graphsdk/LibraryTest.java
The goal of this PR is to implement exception handing for jni
Closes #65 
- created Java specific exceptions
- throwing exceptions from jni side
- changed mutex to RWLock for memory states
- some refactor and clean up in apis
- Added input validation in api
> init: jni exception handling

- .github/workflows/pr-verify.yml
- bridge/ffi/src/c_example/main.c
The goal of this PR is to update c ffi test to honor underlying requirement of non zero page hash
> update c tests

- bridge/jni/src/api.rs
- java/lib/src/main/java/io/amplica/graphsdk/Graph.java
The goal of this PR is to ensure that there are no race conditions between reading and writing state and Garbage collection during JNI api execution
related to #14
> some more safety related checks and mechanism

- Makefile
- README.md
- config/README.md
- core/README.md
The goal of this PR is add some high level documents to the repo
related to #79
> init: high level docs

- core/src/api/api.rs
The goal of this PR is to add documentations for SDK APIs
related to #79
> added: api rust docs

- config/src/errors.rs
- config/src/lib.rs
- core/src/dsnp/schema.rs
- core/src/graph/graph.rs
- core/src/graph/key_manager.rs
- core/src/graph/page_capacities.rs
- core/src/graph/shared_state_manager.rs
- core/src/graph/updates.rs
- core/src/graph/user.rs
The goal of this PR is to add more documentation
part of: #79
> add docs to `dsnp-graphsdk-config`

- README.md
The goal of this PR is to add some example of usages in ReadMe
related to #79
> some examples of usage

- config/src/builder.rs
- config/src/lib.rs
- core/src/api/api_types.rs
- core/src/api/mod.rs
- core/src/dsnp/compression.rs
- core/src/dsnp/dsnp_configs.rs
- core/src/dsnp/dsnp_types.rs
- core/src/dsnp/encryption.rs
- core/src/dsnp/pseudo_relationship_identifier.rs
- core/src/graph/mod.rs
- core/src/util/builders.rs
- core/src/util/time.rs
- core/src/util/transactional_hashmap.rs
- core/src/util/transactional_vec.rs
The goal of this PR is to add some more documents
Closes #79
> some more docs

- .github/workflows/pr-verify.yml
- Makefile
- bridge/node/README.md
- bridge/node/js/index.ts
- bridge/node/node-example-client/index.ts
- bridge/node/node-example-client/package-lock.json
- bridge/node/node-example-client/package.json
- bridge/node/node-example-client/tsconfig.json
The goal of this PR is to fix npm package to export graph type and add an example client
> SDK node bridge example client

- .cargo-deny.toml
- .github/workflows/pr-verify.yml
- Makefile
- bridge/node/LICENSE
- bridge/node/node-example-client/package-lock.json
- bridge/node/node-example-client/package.json
- bridge/node/package-lock.json
- bridge/node/package.json
The goal of this PR is to setup cargo deny
Closes #142 
- Also fixes the JS package licenses
> License Checking via Cargo Deny

- config/resources/configs/frequency-rococo.json
The goal of this PR is to update the GraphSDK configuration with the published schema ids for testnet (rococo).
Closes #103
> feat: update with published Rococo schema ids

- config/resources/configs/frequency.json
* Update mainnet config with published schema ids
* Remove public friendship from config
Closes #104
> fix: update mainnet config with actual published schema ids

- java/lib/build.gradle.kts
The goal of this PR is to use a new incremented snapshot for jvm
> Incremented snapshot jvm version

- bridge/node/package.json
The goal of this PR is to allow the latest changes to publish a new npm package
> Bump npm package version

- Cargo.lock
- bridge/common/Cargo.toml
- bridge/ffi/Cargo.toml
- bridge/jni/Cargo.toml
- bridge/node/Cargo.toml
- bridge/node/package-lock.json
- bridge/node/package.json
- config/Cargo.toml
- core/Cargo.toml
- java/lib/build.gradle.kts
- log-result-proc-macro/Cargo.toml
The goal of this PR is bump versions to v1.0.0 so we can release our first stable version.
Closes #173
> bump versions to 1.0.0

- bridge/node/node-example-client/index.ts
- bridge/node/node-example-client/package-lock.json
- bridge/node/node-example-client/package.json
- java/example-graphsdk-client/build.gradle.kts
The goal of this PR is cleanup some left-over updates during last commits.
Related to #180
> some minor fixes

- bridge/node/README.md
The goal of this PR is to fix the api ReadMe for Node bridge
Closes #177
> Fix node api README

- .github/workflows/release.yml
The goal of this PR is to fix the npm publish issue
related to #211
> fix the github ci
